try delete after tests

diff --git a/.github/workflows/PR.yaml b/.github/workflows/PR.yaml
--- a/.github/workflows/PR.yaml
+++ b/.github/workflows/PR.yaml
@@ -157,6 +157,25 @@ jobs:
         run: |
           make argo-workflow-lint
 
+      - name: create example clusters to delete
+        env:
+          INFRA_TOKEN: ${{ secrets.INFRA_TOKEN_DEV }}
+        run: |
+          set +e
+          set -x
+          kubectl -n infra port-forward svc/infra-server-service 8443:8443 > /dev/null 2>&1 &
+          sleep 10
+
+          $INFRACTL create gke-default tstlonglifer --lifespan 8h
+          $INFRACTL create gke-default tstshortlifer --lifespan 30s
+          $INFRACTL create gke-default tstdestroyed --lifespan 2h
+
+          $INFRACTL delete tstdestroyed --json
+
+          $INFRACTL list --all --quiet
+
+          kill %1
+
       - name: Run Go e2e tests
         env:
           INFRA_TOKEN: ${{ secrets.INFRA_TOKEN_DEV }}
@@ -166,3 +185,61 @@ jobs:
           GOPATH=$(go env GOPATH)
           export GOPATH
           make go-e2e-tests
+
+      - name: Wait for cluster
+        run: |
+          set -xo pipefail
+          for I in {1..60}; do
+            ~/.local/bin/infractl get "$CLUSTER_NAME" | tee >( cat >&2 ) | grep READY && break || echo $?
+            sleep 60
+          done
+          ~/.local/bin/infractl artifacts "$CLUSTER_NAME" -d /tmp/
+          kubectl get nodes -o wide || true
+          for I in {1..5}; do
+            kubectl -n infra rollout status deploy/infra-server-deployment --timeout=300s && break || echo $?
+            sleep 60
+          done
+
+      - name: Destroy created clusters still running
+        env:
+          INFRA_TOKEN: ${{ secrets.INFRA_TOKEN_DEV }}
+        run: |
+          set -x
+          kubectl -n infra port-forward svc/infra-server-service 8443:8443 > /dev/null 2>&1 &
+          sleep 10
+
+          echo 'For 30 minutes, list and delete child clusters that are not failed.'
+          for I in {1..30}; do
+            $INFRACTL list --all --quiet
+            count=0
+            # Continue if running or destroying
+            for cluster in $($INFRACTL list --all --quiet --status='READY,CREATING,DESTROYING'); do
+              echo "$(( ++count )): ${cluster}"
+            done
+            if [[ $count -gt 0 ]]; then
+              echo 'Active clusters found. Deleting ...' | tee -a "$GITHUB_STEP_SUMMARY"
+            else
+              echo 'No active clusters found.'
+              break
+            fi
+            # shellcheck disable=SC2086
+            for cluster in $($INFRACTL list --all --quiet --status='READY,CREATING'); do
+              $INFRACTL get "${cluster}" \
+                && $INFRACTL delete "${cluster}"
+            done \
+              | tee -a "$GITHUB_STEP_SUMMARY"
+            echo "(sleep 1 minute then check again. try $I/30)"
+            sleep 60
+          done
+
+          kill %1
+
+      - name: Destroy PR dev cluster
+        run: |
+          ~/.local/bin/infractl delete "$CLUSTER_NAME"
+          echo "Deleted PR dev cluster ${CLUSTER_NAME}" | tee -a "$GITHUB_STEP_SUMMARY"
+
+      - name: Comment on PR
+        run: |
+          gh pr comment "${{ github.event.number }}" \
+            --body "Development cluster deleted."
