run go e2e tests?

diff --git a/.github/workflows/PR.yaml b/.github/workflows/PR.yaml
--- a/.github/workflows/PR.yaml
+++ b/.github/workflows/PR.yaml
@@ -165,17 +165,22 @@ jobs:
         run: |
           make argo-workflow-lint
 
-      - name: Run e2e tests
+      # - name: Run e2e tests
+      #   run: |
+      #     kubectl -n infra port-forward svc/infra-server-service 8443:8443 &
+      #     sleep 5
+
+      #     $INFRACTL whoami || true
+      #     $INFRACTL version || true
+
+      #     make e2e-tests || touch FAIL_BATS_E2E
+      #     kubectl -n infra logs -l app=infra-server --tail=-1
+      #     kill %1
+
+      #     [[ ! -f FAIL_BATS_E2E ]]
+
+      - name: Run Go e2e tests
         run: |
           kubectl -n infra port-forward svc/infra-server-service 8443:8443 &
           sleep 5
-
-          $INFRACTL whoami || true
-          $INFRACTL version || true
-
-          make e2e-tests || touch FAIL_BATS_E2E
-          make go-e2e-tests || touch FAIL_GO_E2E
-          kubectl -n infra logs -l app=infra-server --tail=-1
-          kill %1
-
-          [[ ! -f FAIL_BATS_E2E ]] || [[ ! -f FAIL_GO_E2E ]]
+          make go-e2e-tests
